name: Deploy Torgide Web Application

on:
  workflow_dispatch:
  push:
    branches:
      - main
  workflow_call:

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: './client/package-lock.json'

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Build
        working-directory: ./client
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.API_URL }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_WATER_0CA85CD03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: './client/dist'
          output_location: ''
          skip_app_build: true
